services:
  mysql:
    image: mysql:8.0
    container_name: barber-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: barber_booking
      MYSQL_USER: barberuser
      MYSQL_PASSWORD: barberpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: barber-phpmyadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql

  redis:
    image: redis:7-alpine
    container_name: barber-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  minio:
    # image: minio/minio:latest
    # after RELEASE.2025-04-22T22-12-26Z, minio removed most of the admin UI, if you want to use the admin UI, uncomment the line below
    # image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    # if you uncommented the line above, comment the line below
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: barber-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  mysql_data:
  redis_data:
  minio_data:
