FROM node:20-alpine AS builder
WORKDIR /app
ENV NODE_ENV=development
ARG VITE_API_BASE_URL=http://localhost:3000/api
ARG VITE_MAPIR_API_KEY=
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_MAPIR_API_KEY=$VITE_MAPIR_API_KEY
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine AS runner
WORKDIR /usr/share/nginx/html
COPY docker/frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist ./
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
